/**
 * Ergonomic re-exports of the generated schema types (T016). The four files below are
 * auto-generated by `npm run types` from data/schema/*.json and MUST NOT be hand-edited — import
 * from this barrel instead, which is hand-written and stable across regeneration.
 *
 * "dev-*" = authored shape (what lives in data/), the other pair = built/denormalized shape
 * (what lives in build/) — see data-model.md.
 */
export type { HttpAccessibilitysupportedComDevTestJson as DevTest } from './dev-test';
export type { HttpAccessibilitysupportedComDevFeatureJson as DevFeature } from './dev-feature';
export type { HttpAccessibilitysupportedComTestJson as Test } from './test';
export type {
  HttpAccessibilitysupportedComFeatureJson as Feature,
  Assertion,
  Url,
} from './feature';

export type { ATBrowsers, AssistiveTechnology, Browser } from './at-browsers';
