/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HttpAccessibilitysupportedComTestJson {
  id: string;
  title: string;
  description: string;
  /**
   * Key words that are used to help find features in a search
   */
  keywords?: string[];
  /**
   * path relative to the /data/tests/html directory. References the file that contains the test html.
   */
  html_file: string;
  versions: {
    jaws?: AtVersion;
    nvda?: AtVersion;
    vo_ios?: AtVersion;
    vo_macos?: AtVersion;
    narrator?: AtVersion;
    android?: AtVersion;
    dragon_win?: AtVersion;
    [k: string]: unknown;
  };
  assertions: Assertion[];
  history: History[];
  core_support: {
    [k: string]: unknown;
  };
  extended_support: {
    [k: string]: unknown;
  };
  core_support_string: {
    [k: string]: unknown;
  };
  extended_support_string: {
    [k: string]: unknown;
  };
  supports_at?: ("sr" | "vc")[];
  [k: string]: unknown;
}
export interface AtVersion {
  browsers: {
    chrome?: BrowserVersion;
    and_chr?: BrowserVersion;
    edge?: BrowserVersion;
    firefox?: BrowserVersion;
    and_ff?: BrowserVersion;
    ie?: BrowserVersion;
    ios_saf?: BrowserVersion;
    safari?: BrowserVersion;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface BrowserVersion {
  at_version: string;
  browser_version: string;
  /**
   * The OS version indicates what accessibility APIs are in use
   */
  os_version: string;
  /**
   * The date is required to help us determine which support points have priority for testing.
   */
  date: string;
  [k: string]: unknown;
}
export interface Assertion {
  feature_id: string;
  feature_assertion_id: string;
  /**
   * Must match the ID of a feature. Example: html/div_element
   */
  applies_to?: string;
  references?: string[];
  /**
   * A css selector that determines which elements in the example need to be tested.
   */
  css_target: string;
  /**
   * an example of expected output; does not need to be exact. This can be helpful especially for things like computed accessible names and descriptions.
   */
  expected_value?: string;
  /**
   * an object of AT ids as keys and rationale as values. The presence of a key indicates that the AT is not applicable for the given reason. An example might be vc_ios on the convey_role assertion since vc_ios intentionally does not support this.
   */
  exclude_at?: {
    [k: string]: unknown;
  };
  /**
   * an object of browser ids as keys and rationale as values. The presence of a key indicates that the browser is not applicable for the given reason. An example might be that IE does not support an html5 form control.
   */
  exclude_browsers?: {
    [k: string]: unknown;
  };
  results: {
    jaws?: At;
    nvda?: At;
    vo_ios?: At;
    vo_macos?: At;
    narrator?: At;
    android?: At;
    dragon_win?: At;
    dragon_mac?: At;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface At {
  browsers: {
    chrome?: Browser;
    and_chr?: Browser;
    edge?: Browser;
    firefox?: Browser;
    and_ff?: Browser;
    ie?: Browser;
    ios_saf?: Browser;
    safari?: Browser;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface Browser {
  /**
   * Is the combination of support values for the output array y=yes, p=partial, n=no, na=not-applicable. If partial, please provide extra documentation as to why.
   */
  support: "y" | "p" | "n" | "na" | "u";
  output?: {
    command: string;
    before?: {
      /**
       * Describes the mode that the AT was in before executing the command (usually applies just for screen readers).
       */
      mode: "auto" | "browse" | "forms";
      /**
       * Describes the location of keyboard focus before the command was executed.
       */
      focus_location:
        "before target" | "after target" | "target" | "within target" | "start of target" | "end of target" | "na";
      /**
       * Describes the location of the virtual cursor before the command was executed.
       */
      virtual_location:
        "before target" | "after target" | "target" | "within target" | "start of target" | "end of target" | "na";
      [k: string]: unknown;
    };
    /**
     * Describes the focus/cursor destination after the command.
     */
    after?:
      | "target"
      | "start of target"
      | "end of target"
      | "past target"
      | "before target"
      | "within target"
      | "after target"
      | "na";
    output?: string;
    result: "pass" | "fail" | "partial" | "unknown" | "na";
    /**
     * If support is hidden behind a non-default setting, describe that setting here.
     */
    behind_setting?: string;
    [k: string]: unknown;
  }[];
  /**
   * Any relevant notes. This can be in markdown format.
   */
  notes?: string;
  [k: string]: unknown;
}
export interface History {
  date: string;
  message: string;
  [k: string]: unknown;
}
